### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by Mathieu-R** [Julien00859/Bomberman#1]
Ceci ==> io.send_event("move", [], {direction: "S"})

Fait tout planter :

[INFO] <server.game_manager> Player ID 2 has been killed in game ID 1
[INFO] <sys.stdout> ----------------------------------------
[INFO] <sys.stdout> Exception happened during processing of request from
[INFO] <sys.stdout> ('127.0.0.1', 52818)
Traceback (most recent call last):
  File "c:\users\matte\appdata\local\programs\python\python35-32\Lib\socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
[INFO] <server.game_manager> Game ID 1 has been won by Player ID 1
  File "c:\users\matte\appdata\local\programs\python\python35-32\Lib\socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\matte\Documents\Lab\Projets\Bomberman\venv\lib\site-packages\websocket_server\websocket_server.py", line 136, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "c:\users\matte\appdata\local\programs\python\python35-32\Lib\socketserver.py", line 681, in __init__
    self.handle()
  File "C:\Users\matte\Documents\Lab\Projets\Bomberman\venv\lib\site-packages\websocket_server\websocket_server.py", line 149, in handle
    self.read_next_message()
[INFO] <server.game_manager> Game ID 1 is over
  File "C:\Users\matte\Documents\Lab\Projets\Bomberman\venv\lib\site-packages\websocket_server\websocket_server.py", line 191, in read_next_message
    self.server._message_received_(self, decoded)
  File "C:\Users\matte\Documents\Lab\Projets\Bomberman\venv\lib\site-packages\websocket_server\websocket_server.py", line 100, in _message_received_
    self.message_received(self.handler_to_client(handler), self, msg)
[INFO] <server.game_manager> Player ID 2 removed from game manager
  File "C:\Users\matte\Documents\Lab\Projets\Bomberman\server\web_server.py", line 39, in onmessage
    manager.send_event(client["id"], dictmsg["event"], dictmsg["args"], dictmsg["kwargs"])
  File "C:\Users\matte\Documents\Lab\Projets\Bomberman\server\game_manager.py", line 215, in send_event
    game.run_event(client_id, event, *args, **kwargs)
  File "C:\Users\matte\Documents\Lab\Projets\Bomberman\game\bomberman.py", line 398, in run_event
    getattr(self.players[pid], event)(*args, **kwargs)
  File "C:\Users\matte\Documents\Lab\Projets\Bomberman\game\entities.py", line 14, in move
    if self.isalive and direction in VECTORS:
TypeError: unhashable type: 'list'
[INFO] <sys.stdout> ----------------------------------------

**Comment by Julien00859** [comment]
A corrigé une partie du problème: c8758aa1fda277c3bf2ee2eb797ad9075177c159

**Comment by Julien00859** [comment]
Coincé par #2
